// MT Engine MK2
// Copyleft 2014 the Mojon Twins

// mapa.h
// Fixed map for 48K mono-level games / placeholder
// Loads "map.bin" and "bolts.bin" as generated by map2bin.exe

extern unsigned char map [0];

#asm
	._map
		BINARY "map.bin"
#endasm

#ifndef COMPRESSED_LEVELS
typedef struct {
    unsigned char np, x, y, st;
} BOLTS;
#endif

#define MAX_bolts 0

